name: CI pull request

on:
  push: 
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: macos-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: bundle install

    - name: Run Unit tests via Fastlane
      run: bundle exec fastlane test

    - name: Run Unit tests
      run: ./gradlew testdebugUnitTest

    - name: Android Emulator Runner
      uses: ReactiveCircus/android-emulator-runner@v2.25.0
      with:
        api-level: 28
        script: ./gradlew connectedCheck
